### ISSUE TITLE
unable to create a release

### ISSUE THREAD

**Issue by aussielunix** [AusDTO/graylog-boshrelease#1]
Given I have cloned this repo
And I issue the command `bosh create release --force`
I am given an error of **Sorry, your current directory doesn't look like release directory**

**Comment by aussielunix** [comment]
G`Day @m-richo I think this is to do with a lack of src or blobs dir ?

**Comment by m-richo** [comment]
Thanks for raising this @aussielunix .  I'm pretty sure it's the absense of a `src` folder.  i'll add a `/src/.gitkeep` file to fix it.

Cheers,
Michael
