### ISSUE TITLE
Add GeoIP database

### ISSUE THREAD

**Issue by bladeswords** [AusDTO/graylog-boshrelease#10]
A very useful feature of Graylog2 is the ability to perform GeoIP lookup on IP addresses.  This feature is enabled, but the database is missing from the release.  Information is avaliable at http://docs.graylog.org/en/2.3/pages/geolocation.html

Additionally the database should be updated regularly, probably with a cronjob (or maybe include with the GeoIP package?)

**Comment by gordcorp** [comment]
Sounds handy, I will look into it

**Comment by bladeswords** [comment]
Let me know if you need help/assistance - I don't know BOSH, but I have got my local version of graylog configured.

**Comment by gordcorp** [comment]
Included in [release v0.0.7](https://github.com/AusDTO/graylog-boshrelease/releases/tag/v0.0.7)
